<dl class="payment-method">
    <dt class="title"><strong><?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?></strong></dt>
    <?php if ($block->isPending()): ?>
        <dd class="content">
            <br>
            <p><?php echo $block->getDigitableLine() ?></p>
            <br/>
            <a class="action print btn primary" href="<?php echo $block->getPaymentUrl() ?>" target="_blank">
                <span><?php echo __('Print PostPay') ?></span>
            </a>
        </dd>
    <?php endif; ?>
</dl>